### ISSUE TITLE
pywal integration

### ISSUE THREAD

**Issue by hbthen3rd** [hbthen3rd/dotfiles#36]
Integrate [`pywal`](https://github.com/dylanaraps/pywal) to generate color scheme base on wallpaper.

### Keep in mind:
- Might need to download from head as the pip release is not functional out-of-the box for macOS: https://github.com/dylanaraps/pywal/wiki/Installation#MacOS
- Make sure we can fallback to standard/established color schemes (gruvbox, dracula, tomorrow, base-16, etc.)
- Make sure `neovim` still have a transparent background
- Might need to switch `btop` to **TTY** theme
- Investigate if we could/should theme: `ranger`, `lazygit`, `bat`, `eza`, `taskwarrior`, `taskwarrior-tui`

### To-do:
- [ ] Convert [`.config/colors.sh`](https://github.com/hbthen3rd/dotfiles/blob/master/.config/colors.sh) to `pywal`'s format (`color0` - `color15`)
- [ ] `neovim` integration with [`wally.nvim`](https://github.com/atalazer/wally.nvim)
- [ ] Firefox integration with [Pywalfox](https://github.com/Frewacom/pywalfox)
- [ ] Alfred integration with [AlfredPywal](https://github.com/metafates/AlfredPywal)

**Comment by albert-ying** [comment]
This is what I add to `color.sh`

works well for me so far

```
source $HOME/.cache/wal/colors.sh

export COLOR_BLACK=${color0/\#/0xff}
export COLOR_WHITE=${color15/\#/0xff}
export COLOR_RED=${color9/\#/0xff}
export COLOR_GREEN=${color10/\#/0xff}
export COLOR_BLUE=${color11/\#/0xff}
export COLOR_YELLOW=${color12/\#/0xff}
export COLOR_ORANGE=${color13/\#/0xff}
export COLOR_MAGENTA=${color14/\#/0xff}
export COLOR_GREY=${color7/\#/0xff}
export COLOR_SKY=${color3/\#/0xff}
export COLOR_PINK=${color4/\#/0xff}
export COLOR_TRANSPARENT=0x00000000

export COLOR_BLACK_BRIGHT=${color0/\#/0xff}
export COLOR_WHITE_BRIGHT=${color15/\#/0xff}
export COLOR_RED_BRIGHT=${color9/\#/0xff}
export COLOR_GREEN_BRIGHT=${color10/\#/0xff}
export COLOR_BLUE_BRIGHT=${color11/\#/0xff}
export COLOR_YELLOW_BRIGHT=${color12/\#/0xff}
export COLOR_ORANGE_BRIGHT=${color13/\#/0xff}
export COLOR_MAGENTA_BRIGHT=${color14/\#/0xff}
export COLOR_GREY_BRIGHT=${color7/\#/0xff}
export COLOR_SKY_BRIGHT=${color3/\#/0xff}
export COLOR_PINK_BRIGHT=${color4/\#/0xff}

export COLOR_BACKGROUND=${color0/\#/0xff}
export COLOR_FOREGROUND=${color15/\#/0xff}

export COLOR_ACCENT=${color1/\#/0xff}
export COLOR_ACCENT_BRIGHT=${color14/\#/0xff}
```

![CleanShot 2023-10-25 at 02 18 55@2x](https://github.com/hbthen3rd/dotfiles/assets/59846322/09549a25-3864-4613-b543-61cbadaa7ce9)

![CleanShot 2023-10-25 at 02 21 15@2x](https://github.com/hbthen3rd/dotfiles/assets/59846322/a742f5ae-510b-4277-8404-544ce67a5bc6)

**Comment by hbthen3rd** [comment]
Oh, I like that idea. Here's my WIP so far:

### With preset color schemes:
<img width="1710" alt="Screenshot 2023-10-25 at 12 03 23 AM" src="https://github.com/hbthen3rd/dotfiles/assets/13052949/4ceb307a-d0ea-48e2-920e-a7abe0b32926">
<img width="1710" alt="Screenshot 2023-10-25 at 12 05 04 AM" src="https://github.com/hbthen3rd/dotfiles/assets/13052949/5003637b-bc6c-400c-86c3-58e057ca25bc">

### With wallpaper color schemes:
<img width="1710" alt="Screenshot 2023-10-24 at 11 53 25 PM" src="https://github.com/hbthen3rd/dotfiles/assets/13052949/7ba3497a-dddc-4d7a-ab81-2cc2c97a014e">
<img width="1710" alt="Screenshot 2023-10-24 at 11 55 03 PM" src="https://github.com/hbthen3rd/dotfiles/assets/13052949/4a70554c-f208-40a1-8c6a-27c6b08680cf">
<img width="1710" alt="Screenshot 2023-10-24 at 11 58 17 PM" src="https://github.com/hbthen3rd/dotfiles/assets/13052949/a3570ed9-0683-4174-8cd4-b507b7ff2ff5">
<img width="1710" alt="Screenshot 2023-10-24 at 11 59 14 PM" src="https://github.com/hbthen3rd/dotfiles/assets/13052949/32e4e896-93dd-46e1-8e0c-03a24a0fb65f">
